spring.application.name=vote-consumer
server.port=8081

spring.data.mongodb.uri=mongodb://admin:123@localhost:27017/sicred?authSource=admin
spring.data.mongodb.auto-index-creation=true

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=vote-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest

# Consumer
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.challenge.voteconsumer.model
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.apache.kafka.common.serialization.ByteArrayDeserializer

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

user.api.url=http://localhost:8082
