services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
      - TZ=America/Sao_Paulo

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  kafka:
    container_name: kafka
    image: apache/kafka:latest
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CLUSTER_ID: 'sicred-cluster-1'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9092,
        EXTERNAL://0.0.0.0:9094,
        CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://kafka:9092,
        EXTERNAL://localhost:9094
        
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        CONTROLLER:PLAINTEXT,
        EXTERNAL:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 1

    volumes:
      - ./kafka_data:/var/lib/kafka/data

  core-api:
    build:
      context: core
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:123@mongodb:27017/sicred?authSource=admin
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - USER_API_URL=http://user-api:8082
      - TZ=America/Sao_Paulo
    depends_on:
      - mongodb
      - kafka
      - redis
      - user-api

  vote-consumer:
    build:
      context: vote-consumer
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:123@mongodb:27017/sicred?authSource=admin
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - USER_API_URL=http://user-api:8082
    depends_on:
      - mongodb
      - kafka
      - user-api

  user-api:
    build:
      context: user-api
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
