spring.application.name=core
spring.data.mongodb.uri=mongodb://admin:123@localhost:27017/sicred?authSource=admin
server.port=8080

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.data.redis.host=localhost
spring.data.redis.port=6379

agenda.scheduler.interval=60000
